import fs from 'node:fs';
import path from 'node:path';
import { apkSlug } from './util.js';

const EXCLUDED_DIRS = new Set(['build', '.gradle', '.cxx', '.kotlin']);
const EXCLUDED_FILES = new Set(['.forge-meta.json', 'local.properties']);

export function exportRepo(options = {}) {
  const { sourceDir, outDir, appName, description = '', packageName = '', versionName = '' } = options;
  if (!sourceDir) throw new Error('exportRepo requires sourceDir');

  const src = path.resolve(sourceDir);
  if (!fs.existsSync(path.join(src, 'gradlew')) || !fs.existsSync(path.join(src, 'app/build.gradle.kts'))) {
    throw new Error(`Not a WebShell Forge project (missing gradlew or app/build.gradle.kts): ${src}`);
  }

  const dest = path.resolve(outDir);
  if (fs.existsSync(dest)) {
    throw new Error(`Export target already exists: ${dest}`);
  }

  fs.mkdirSync(dest, { recursive: true });
  copyFiltered(src, dest);
  fs.chmodSync(path.join(dest, 'gradlew'), 0o755);

  writeWorkflow(dest, { slug: apkSlug(appName || path.basename(src)) });
  writeReadme(dest, { appName, description, packageName, versionName });

  return { outDir: dest };
}

function copyFiltered(src, dest, prefix = '') {
  for (const entry of fs.readdirSync(src, { withFileTypes: true })) {
    const rel = prefix ? `${prefix}/${entry.name}` : entry.name;
    if (entry.isDirectory()) {
      if (EXCLUDED_DIRS.has(entry.name)) continue;
      copyFiltered(path.join(src, entry.name), path.join(dest, entry.name), rel);
    } else if (entry.isFile()) {
      if (EXCLUDED_FILES.has(entry.name)) continue;
      fs.mkdirSync(path.dirname(path.join(dest, entry.name)), { recursive: true });
      fs.copyFileSync(path.join(src, entry.name), path.join(dest, entry.name));
      fs.chmodSync(path.join(dest, entry.name), fs.statSync(path.join(src, entry.name)).mode);
    }
  }
}

function writeWorkflow(dest, { slug }) {
  fs.mkdirSync(path.join(dest, '.github', 'workflows'), { recursive: true });
  const yml = `name: Build APK

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: assembleDebug
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-\${{ runner.os }}-\${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: gradle-\${{ runner.os }}-

      - name: Accept Android SDK licenses
        run: yes | "$ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager" --licenses > /dev/null || true

      - name: Build debug APK
        run: ./gradlew assembleDebug --no-daemon --stacktrace

      - uses: actions/upload-artifact@v4
        with:
          name: ${slug}-debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk
          if-no-files-found: error
`;
  fs.writeFileSync(path.join(dest, '.github', 'workflows', 'build.yml'), yml);
}

function writeReadme(dest, { appName, description, packageName, versionName }) {
  const md = `# ${appName || 'WebShell App'}

${description || '_No description provided._'}

Native Android app built from plain **HTML / CSS / JS** with
[WebShell Forge](https://github.com/s17labs/webshell-forge) on top of the minimal
[s17labs/webshell](https://github.com/s17labs/webshell) WebView template.

[![Build APK](https://github.com/YOUR_USERNAME/${apkSlug(appName || 'webshell-app')}/actions/workflows/build.yml/badge.svg)](https://github.com/YOUR_USERNAME/${apkSlug(appName || 'webshell-app')}/actions/workflows/build.yml)

## Get the APK

Every push builds a debug APK via GitHub Actions — grab it from
**Actions → Build APK → latest run → Artifacts**.

Or build locally (JDK 17 + Android SDK with platform 35):

\`\`\`bash
./gradlew assembleDebug
# → app/build/outputs/apk/debug/app-debug.apk
\`\`\`

## Customize your app

Your code lives in \`app/src/main/assets/www/\`:

| File | Purpose |
|---|---|
| \`index.html\` | entry point |
| \`style.css\` | styles |
| \`app.js\` | logic |
| \`bridge.js\` | JS ↔ native bridge (keep it included) |

Call native features from JS, e.g. \`NativeBridge.toast('hi!')\`.
The app already has \`INTERNET\` permission — fetch away.

---

- package: \`${packageName}\`
- version: ${versionName}
- generated by [WebShell Forge](https://github.com/s17labs/webshell-forge)
`;
  fs.writeFileSync(path.join(dest, 'README.md'), md);
}
